INSERT INTO champions (name, image, title, enemytips, lore, passive_name, passive_image, passive_description, spells_q_name, spells_q_image, spells_q_description, spells_w_name, spells_w_image, spells_w_description,
    spells_e_name, spells_e_image, spells_e_description,
    spells_r_name, spells_r_image, spells_r_description)
VALUES
('Ho0dLuM',
  'Yasuo.png',
  'World Breaker',
  'Avoid his world smash attack',
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  'Iron Ambassador',
  'Poppy_Passive.png',
  'Poppy throws her buckler, gaining range and bonus magic damage. The buckler lands at a nearby location and Poppy can pick it up to gain a shield. Enemies can step on the buckler to destroy it.',
  'Steel Tempest',
  'YasuoQW.png',
  'A skillshot basic attack. After two successful Steel Tempests, the next fires a tornado that knocks enemies Airborne.',
  'Unbreakable',
  'BraumE.png',
  'Braum raises his shield in a direction for several seconds, intercepting all projectiles causing them to hit him and be destroyed. He negates the damage of the first attack completely and reduces the damage of all subsequent attacks from this direction.',
  'Elastic Slingshot',
  'ZacE.png',
  'Zac attaches his arms to the ground and stretches back, launching himself forward.',
  'Last Breath',
  'YasuoRKnockUpComboW.png',
  'Moves to a unit and strikes them repeatedly for heavy damage. Can only be cast on Airborne targets.')
